### ISSUE TITLE
Line too long error

### ISSUE THREAD

**Issue by mathieumg** [STRML/JSXHint#13]
I understand this might be a limitation, but since .jsx files get transformed prior to being passed through JSHint, it's not unusual for a line to get lengthier in the process (even if so slightly) and that becomes an issue if the original JSX line is close to the `"maxlen"` value. 
Besides obvious "workarounds" (changing that value, shortening the original lines even if below the limit), is there anything that could be done to resolve this? 

I figure there might be, since there is already a mapping from JSHint column number errors back to the original JSX column numbers so it could become an ignored error if the original column is below the set limit. I'm not sure if JSXHint is aware of the linting options however, but if it isn't I wouldn't mind having to set that column max length value again in JSXHint as a workaround, even if it implicates duplicating information... Of course, if JSXHint already knows the linting options, this should be doable, is that correct?

**Comment by mathieumg** [comment]
Just wanted to chime in and say that I have since switched over to ESLint, feel free to keep this open or not. I personally don't need this feature anymore. Thank you!

**Comment by fbm-static** [comment]
ESLint for the win!!

**Comment by STRML** [comment]
:+1: Use ESLint.
