### ISSUE TITLE
newCap error

### ISSUE THREAD

**Issue by amankapur** [STRML/JSXHint#20]
I want to enable newCap in my .jshintrc to true but with jsx Components it fails as it sees any React Component being used without a 'new' infront of it and a capitalized letter. 

This issue was also prevailent in the depricated version of jsxhint here https://github.com/CondeNast/JSXHint/issues/16

Am I missing something or is this a valid issue?

**Comment by STRML** [comment]
See https://github.com/STRML/JSXHint/commit/05212f6ccfafe401779b296f97924c30fdd66fb2: Use ESLint.
