### ISSUE TITLE
Option: "quotmark": "single"

### ISSUE THREAD

**Issue by OliverJAsh** [STRML/JSXHint#21]
The `quotmark` option, when set to `single`, will cause linter errors to be thrown. I understand this is because JSX compiles with double quotation marks.

**Comment by STRML** [comment]
This is actually fixed in the newest JSTransform: See #73.

**Comment by mondaychen** [comment]
@STRML #73 only allows the use of `"quotmark" : "double"` which fixes #72 . But thanks a lot for mentioning ESLint there which seems to be a great alternative. Will try it at work on Monday.
