### ISSUE TITLE
jsxhint ignoring .jsxhintignore file

### ISSUE THREAD

**Issue by koulmomo** [STRML/JSXHint#25]
hey,
jsxhint seems to ignore my `.jsxhintingore` file but respects a `.jshintignore` file.

Is this the intended behavior? If so, the README should update the [usage section](https://github.com/STRML/JSXHint#usage)

**Comment by STRML** [comment]
I was sloppily replacing all instances of `jshint` with `jsxhint` in the help output, which lead to the transformation of `.jshintignore` to `.jsxhintignore`, which this project doesn't use. 

Thanks for bringing it to my attention.
