### ISSUE TITLE
Mismatched line numbers to errors

### ISSUE THREAD

**Issue by Ceane** [STRML/JSXHint#38]
Using the `--6to5` option gives correct but mismatched feedback. 

```javascript
class LintMe {
    constructor() {
      var test;
    } //feedback here
} // and here
```

**Comment by Ceane** [comment]
A new version of [ESLint](http://eslint.org/blog/2015/01/eslint-0.12.0-released/) has been released today that supports JSX.

**Comment by STRML** [comment]
Impressive! I'll try it out... if it does the job, I will sunset this
project and sublimelinter-jsxhint.

**Comment by ruswerner** [comment]
@STRML If you pass `{sourceMap:true}` to `to5.transform(...)` then it will generate source maps and the resulting object will have a `.map`. I'm not that familiar with jshint, however if it supports a source map, then you should be able translate the line/col numbers back. Or you could possibly do it manually after the jshint output is received.

**Comment by STRML** [comment]
See https://github.com/STRML/JSXHint/commit/05212f6ccfafe401779b296f97924c30fdd66fb2: Use ESLint. There will always be weird errors like this. While we can probably fix the line numbers, we're going to get all kinds of fun like #17. ESLint does it properly.
