### ISSUE TITLE
Trailing , in destructuring assignments causes false positives in following lines. 

### ISSUE THREAD

**Issue by clentfort** [STRML/JSXHint#50]
When having a trailing comma behind the last variable in a destructuring assignment from an object it causes jsxhint to report false errors on the following lines. This did not cause any problems in previous versions of jsxhint (I tried v0.4.15). jshint does only report the the line with the trailing comma.

jsxhint version: `JSXHint v0.12.1 (jshint v2.6.0)`

**Example code:**

    function returnObject() {
    }

    var {
      a,
      b,
    } = returnObject();

    function antoherFunction() {
    }

**jsxhint output:**

    error_destructuring.js: line 7, col 1, Expected an identifier and instead saw '}'.
    error_destructuring.js: line 7, col 3, Expected ',' and instead saw '='.
    error_destructuring.js: line 7, col 17, Expected ',' and instead saw '('.
    error_destructuring.js: line 7, col 18, Expected an identifier and instead saw ')'.
    error_destructuring.js: line 7, col 19, Expected ',' and instead saw ';'.
    error_destructuring.js: line 9, col 1, Expected an identifier and instead saw 'function' (a reserved word).
    error_destructuring.js: line 9, col 10, Expected ',' and instead saw 'antoherFunction'.
    error_destructuring.js: line 9, col 25, Expected an identifier and instead saw '('.
    error_destructuring.js: line 9, col 26, Expected ',' and instead saw ')'.
    error_destructuring.js: line 9, col 28, Expected an identifier and instead saw '{'.
    error_destructuring.js: line 10, col 2, Missing semicolon.

    11 errors

**jshint output:**

    error_destructuring.js: line 7, col 1, Expected an identifier and instead saw '}'.

    1 error

**config.json:**

    {
      "esnext": true
    }

**Comment by caitp** [comment]
feel free to review the fix. on the bonus side, trailing commas are not actually allowed in array destructuring expressions (weirdly!) but, the error message should be a lot easier to understand now in that case.

**Comment by STRML** [comment]
Thanks. Looks like this is working properly with the newest JSHint, so no more errors. Looks like the jsx transformer got really confused on the destructuring operator.
