### ISSUE TITLE
jsxhint with glob pattern tries to lint other than .js and .jsx files

### ISSUE THREAD

**Issue by kimmobrunfeldt** [STRML/JSXHint#52]
Running `jsxhint src/**/*` lints **all** files, not just .js and .jsx files.

```
➜  board git:(node) ✗ jsxhint --version
JSXHint v0.11.1 (jshint v2.6.0)
```

From stdout:
```
src/frontend/styles/variables.styl: line 1, col 9, Expected an identifier and instead saw '#'.
src/frontend/styles/variables.styl: line 1, col 10, Missing semicolon.
src/frontend/styles/variables.styl: line 1, col 10, Expected an assignment or function call and instead saw an expression.
src/frontend/styles/variables.styl: line 1, col 16, Missing semicolon.
src/frontend/styles/variables.styl: line 2, col 12, Unexpected '5'.
src/frontend/styles/variables.styl: line 2, col 11, Expected an identifier and instead saw '#'.
src/frontend/styles/variables.styl: line 2, col 12, Missing semicolon.
src/frontend/styles/variables.styl: line 3, col 10, Unexpected '2'.
src/frontend/styles/variables.styl: line 3, col 9, Expected an identifier and instead saw '#'.
src/frontend/styles/variables.styl: line 3, col 10, Missing semicolon.
src/frontend/styles/variables.styl: line 4, col 11, Expected an identifier and instead saw '#'.
src/frontend/styles/variables.styl: line 4, col 12, Missing semicolon.
src/frontend/styles/variables.styl: line 4, col 12, Expected an assignment or function call and instead saw an expression.
src/frontend/styles/variables.styl: line 4, col 18, Missing semicolon.
src/frontend/styles/variables.styl: line 5, col 8, Expected an identifier and instead saw '#'.
src/frontend/styles/variables.styl: line 5, col 9, Missing semicolon.
src/frontend/styles/variables.styl: line 5, col 9, Expected an assignment or function call and instead saw an expression.
src/frontend/styles/variables.styl: line 5, col 15, Missing semicolon.
src/frontend/styles/variables.styl: line 1, col 1, '$pink' is not defined.
src/frontend/styles/variables.styl: line 1, col 10, 'C4558C' is not defined.
src/frontend/styles/variables.styl: line 2, col 1, '$purple' is not defined.
src/frontend/styles/variables.styl: line 3, col 1, '$blue' is not defined.
src/frontend/styles/variables.styl: line 4, col 1, '$orange' is not defined.
src/frontend/styles/variables.styl: line 4, col 12, 'E4872C' is not defined.
src/frontend/styles/variables.styl: line 5, col 1, '$red' is not defined.
src/frontend/styles/variables.styl: line 5, col 9, 'B90E23' is not defined.
```

**Comment by STRML** [comment]
Could you try this with the latest version?

**Comment by kimmobrunfeldt** [comment]
I tried with version:

    "jsxhint": "STRML/JSXHint#master",

and still get the same result.

**Comment by saebekassebil** [comment]
I have a different problem where

    jsxhint index.jsx js/**/*

does not lint anything at all - just returns silently?

**Comment by percyhanna** [comment]
I have a different glob related problem. If run with a glob such as `assets/javascript/**/*`, it only lints one folder depth down. In other words, it will lint `assets/javascript/views/something.jsx` but not `assets/javascript/views/something/something-else.jsx`.

**Comment by percyhanna** [comment]
So in my case, it's likely just a Bash escaping issue. Not sure about the other problems described here.

**Comment by gvn** [comment]
I'm getting errors reported in LESS files when I run:

`jsxhint --jsx-only www_src/pages/**/*`

File tree:

```bash
www_src/pages/
├── discover
│   ├── discover.jsx
│   └── discover.less
├── editor
│   ├── editor.jsx
│   └── editor.less
├── make
│   ├── make.jsx
│   └── make.less
├── map
│   ├── grid.jsx
│   ├── map.jsx
│   ├── map.less
│   ├── page.jsx
│   └── slot.jsx
├── project
│   ├── blocks
│   │   ├── generator.js
│   │   ├── image.jsx
│   │   ├── link.jsx
│   │   └── text.jsx
│   ├── positionable.jsx
│   ├── project.jsx
│   ├── project.less
│   └── touchhandler.js
└── tinker
    ├── tinker.jsx
    └── tinker.less
```

Version: `JSXHint v0.14.0 (jshint v2.7.0)` (OSX 10.10.2)

**Comment by STRML** [comment]
The `--jsx-only` option will only *transform* files with the `.jsx` extension, but using a glob like that will still attempt to lint all files. Try `jsxhint www_src/pages`, which should work fine. JSHint supports a folder param, and will recursively run on all files with supported extensions (`.js`, and we [add .jsx](https://github.com/STRML/JSXHint/blob/9de98e059a84f834db4659d8b34528089ce5fd06/cli.js#L107)).

That is the reason for the `--jsx-only` option; previously we would look for the pragma in `.js` files and assume all `.jsx` files should be transformed, but now that the pragma has been removed we pass all files through the transformer.

**Comment by STRML** [comment]
@percyhanna Just `jsxhint assets/javascript`.

**Comment by percyhanna** [comment]
I've elected to use a more explicit `assets/javascript/**/*.js*` for now, as this also excludes some other JS-like files that I don't need to lint.

**Comment by STRML** [comment]
To clarify; only use globs if you have a more complicated use case (a small subset of the population). Otherwise, just point jsxhint to the containing folder, much like you would with jshint.

When you use a glob like this, bash will expand the command to list all the files by name, and jsxhint will happily lint them all regardless of extension. We don't check extension if exact file names are passed. The same happens if you do `jshint *`.

**Comment by gvn** [comment]
Hmm, interesting. Thanks @STRML!

**Comment by STRML** [comment]
I've updated the readme to make this more obvious; thanks for recognizing the oversight everyone.
