### ISSUE TITLE
Possible strict violation

### ISSUE THREAD

**Issue by deser** [STRML/JSXHint#60]
Such valid es6 construction gives error when linting:
export default class {

    constructor(settings)
    {
        super();                                                               // Possible strict violation.
        settings = settings || {}; 
        this.validationFuncs = settings.validationFuncs;  // Possible strict violation.
        this.control = settings.control;                              // Possible strict violation.
    }
....

I run jsxhint with these flags: --harmony --es6module

**Comment by STRML** [comment]
Could you post the full code? I am not seeing the strict violation errors.

For example:

```javascript
class Foo extends Bar {
  constructor(settings)
  {
      super();                                                               // Possible strict violation.
      settings = settings || {};
      this.validationFuncs = settings.validationFuncs;  // Possible strict violation.
      this.control = settings.control;                              // Possible strict violation.
  }
}
```
