### ISSUE TITLE
Use jstransform in lieu of react-tools

### ISSUE THREAD

**Issue by danvk** [STRML/JSXHint#64]
Facebook is in the process of [deprecating react-tools in favor of jstransform][1]. In order to use a new feature of FlowType and keep my linting, I need jsxhint to support running code through jstransform, rather than react-tools' jsx.

This could be done via a `--jstransform` flag, much like the current `--babel` flag.

cc @zpao @jeffmo

[1]: https://github.com/facebook/flow/issues/267#issuecomment-97236685

**Comment by STRML** [comment]
That sounds good. If the behavior is the same I can just change the default behavior to use jstransform.

**Comment by zpao** [comment]
There are a couple small differences but they are mostly the same. See https://github.com/facebook/jstransform#migration-guide for details on migrating.

**Comment by STRML** [comment]
Cool. All tests pass with the change. Will roll it into the next release. Until then it should be fine to npm install from master.
