### ISSUE TITLE
Error when using --babel --babel-experimental

### ISSUE THREAD

**Issue by vmsp** [STRML/JSXHint#65]
When using jsxhint with the options mentioned I get a really long error message that starts with
```
Error: Deprecated option experimental: use `--stage 0`/`{ stage: 0 }`"
```
I'm using babel 5.3.3

**Comment by STRML** [comment]
Yeah, I'll update. Babel changed this option around.

**Comment by vmsp** [comment]
I'll send you a pull request in a jiffy.

**Comment by STRML** [comment]
It's okay, I'm working on it. I see a test failure with new Babel though.

**Comment by STRML** [comment]
Ah. Exponentiation is now stage 2 with babel. We need to test a new feature.

I'll push a new version in about 10min.

**Comment by vmsp** [comment]
What error are you getting? I'm just using { stage: 0 } and the tests pass.

**Comment by STRML** [comment]
This error: https://github.com/babel/babel/issues/1538. I will publish when babel pushes a new minor version so the tests pass properly.

**Comment by STRML** [comment]
This is in `0.15.0` - thanks!
