### ISSUE TITLE
Ignoring "React is not defined"

### ISSUE THREAD

**Issue by Zacqary** [STRML/JSXHint#66]
I'm using JSX decoupled from React in one of my projects. Is there any configuration flag that can get jsxhint to ignore an undefined `React`?

**Comment by Zacqary** [comment]
Sorry, duh, it'd be `globals React` obviously.

I wonder if having built-in checking for React would warrant a different directive than `globals` just for semantic purposes. Either way, this is a perfectly fine workaround for now.

**Comment by STRML** [comment]
You could define it as a global in your .jshintrc.

```json
{
  "globals": { "React": false }
}
```

See http://jshint.com/docs/options/#globals
