### ISSUE TITLE
getting `Script URL` error? Don't know how to fix.

### ISSUE THREAD

**Issue by alecklandgraf** [STRML/JSXHint#67]
I get an error `Script URL` for what looks like some benign code in my `.jsx` file with Sublime JSX linter for my `className` with spaces and hyphens.

I tried single and double quotes. I could set `className` to a var.

```jsx
<li className={prevDisabled}><a href onClick={this.prevPage}><i className='fa fa-angle-double-left'></i> Previous</a></
<li className={nextDisabled}><a href onClick={this.nextPage}>Next <i className="fa fa-angle-double-right"></i></a></li>
```

![betable_jsx_ _seed_and_many_incorrect__strings_must_use_singlequote__errors_ _issue__19_ _sublimelinter_sublimelinter-jsxhint_and_1__bash](https://cloud.githubusercontent.com/assets/2336595/7692540/436a2970-fd7a-11e4-958e-97a9a8257fd1.png)

**Comment by STRML** [comment]
I'll be honest, I have no idea what that is. Can you try manually converting it to `js` (using react-tools) and then running jshint on it? Or post a minimal reproducing example.

**Comment by alecklandgraf** [comment]
Thanks for leading me in the right direction. `jslint` and `jsxhint` were pointing pointing to the compiled JS file's column position versus the **jsx** file's position, which is why the error looked like it was within the `className`, but instead was really throwing a warning on the `href`.

The error comes from using the following technique to allow for an `a` element to have a `cursor: pointer` without setting a style for that in places where `href=""` and `href="#"` won't work.

```jsx
<a href="javascript:void(0);" onClick={this.nextPage}>Next <i className="fa fa-angle-double-right"></i></a>
```

which becomes

```js
React.createElement("a", {href: "javascript:void(0);", onClick: this.nextPage}, "Next ", React.createElement("i", {className: "fa fa-angle-double-right"}))
```

This is a pain, because to avoid the error you'll need to conditionally add the cursor style:

```jsx
var nextStyle = nextDisabled ? {} : {cursor: "pointer"};
return (
  <a style={nextStyle} onClick={this.nextPage}>Next <i className="fa fa-angle-double-right"></i></a>
  )
```
