### ISSUE TITLE
"Bad invocation" when calling "import"-ed module function (with --babel flag)

### ISSUE THREAD

**Issue by tlrobinson** [STRML/JSXHint#69]
I'm not sure if this needs to be solved in JSXHint, JSHint, or Babel, but calling a function imported as the default export object results in a W067 "Bad invocation" error:

```
import $ from 'jquery';
$('whatever');
```

This is the code generated by Babel:

```
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }
var _jquery = require("jquery");
var _jquery2 = _interopRequireDefault(_jquery);
(0, _jquery2["default"])("whatever");
```

Temporary workaround (in environments that use `require` like node, webpack, browserify, etc):

```
var $ = require('jquery');
$('whatever');
```

or

```
import jQuery from 'jquery';
var $ = jQuery;
$("whatever");
```

**Comment by STRML** [comment]
I'd recommend ESLint. These kind of syntax transformations get hairy and lead to bad errors all the time. JSXHint is pretty limited in what it can do and ESLint does it correctly.

See https://medium.com/@dan_abramov/lint-like-it-s-2015-6987d44c5b48 for a pretty good synopsis on switching.

**Comment by tlrobinson** [comment]
Ok thanks. I actually tried switching to ESLint but was frustrated by the large number of differences in default rules that were enabled. Any suggestions on migrating?

**Comment by STRML** [comment]
Nope, you just have to sort of power through. The nice thing is that the
rule name is always in the warning/error. It took me a little while to
understand the rule syntax (2: error, 1: warning, 0:ignore) but once you
do, it's great.

ESLint has a lot of new rules that I really enjoy as well.
