### ISSUE TITLE
"foo is already defined" (W004) due to Babel naming anonymous functions

### ISSUE THREAD

**Issue by tlrobinson** [STRML/JSXHint#70]
The following results in a "'foo' is already defined. (W004)"  error when run with the `--babel` flag:

```
var bar = {
    foo: function() {
        var foo = 1;
    }
};
```

This is likely due to Babel giving the anonymous function the same name as the property it's being assigned to:

```
var bar = {
    foo: function foo() {
        var foo = 1;
    }
};
```

**Comment by STRML** [comment]
Please see the answer to [your previous issue](https://github.com/STRML/JSXHint/issues/69#issuecomment-110439137).

In general, if you want to keep using JSXHint, you can do this by adjusting your `.jsxhintrc` to ignore these types of errors, or use rule comments. Otherwise please switch to ESLint.
